### ISSUE TITLE
mitochondrial genes

### ISSUE THREAD

**Issue by olechnwin** [wurmlab/flo#29]
Hi,
This is more of a question than an issue. I just realized that none of the mitochondrial genes were lifted. In the unlifted file, many of them are annotated as deleted/partially deleted in new. I'm just wondering if this is inherent due to the way the algorithm works? Thank you.

**Comment by yeban** [comment]
Could be. For example, one or more [NUMT](https://en.wikipedia.org/wiki/NUMT) can offer an equally good alternative alignment and the chaining step would no longer know which one to pick resulting in smaller chains, which can explain partial deletions. This is just a hypothesis instead of knowing for sure. You could try running flo separately for mitochondrial genome and see if that helps (I would love to know the outcome if you do end up trying this).

**Comment by olechnwin** [comment]
@yeban, thanks for your suggestion. 
Just to clarify, were you suggesting to run flo with only the mitochondrial genes in the gff file?

**Comment by yeban** [comment]
No, I meant try running flo with only the mitochondrial  sequences in the FASTA files. Non mitochondrial genes in the gff file will anyway end up in unlifted.gff.
